// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDDnuF-WDmw8Rw5CdatlbxDwFqc2IVhFHA",
    appId: '1:21850787243:web:d8323b9af24839e488d6ee',
    messagingSenderId: '21850787243',
    projectId: 'clara1-a019a',
    authDomain: 'clara1-a019a.firebaseapp.com',
    storageBucket: 'clara1-a019a.appspot.com',
    measurementId: 'G-916YK2PX1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgjlMmnoE7LObeL46JZQhXChct6xp0ljs',
    appId: '1:21850787243:android:fe9bc1b259f8737488d6ee',
    messagingSenderId: '21850787243',
    projectId: 'clara1-a019a',
    storageBucket: 'clara1-a019a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpPNzXCs4755X6jJ1ULl4VeJI4SHcA3pU',
    appId: '1:21850787243:ios:187fd89e0563be0b88d6ee',
    messagingSenderId: '21850787243',
    projectId: 'clara1-a019a',
    storageBucket: 'clara1-a019a.appspot.com',
    iosBundleId: 'com.example.neuro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpPNzXCs4755X6jJ1ULl4VeJI4SHcA3pU',
    appId: '1:21850787243:ios:a57a21ff31a8d66c88d6ee',
    messagingSenderId: '21850787243',
    projectId: 'clara1-a019a',
    storageBucket: 'clara1-a019a.appspot.com',
    iosBundleId: 'com.example.neuro.RunnerTests',
  );
}
